version: '3'

services:
    app:
        #restart: always
        container_name: 'go-api'
        build: './app'
        expose:
            - 8080
        links:
            - nginx
            - mongodb
        depends_on:
            - mongodb
        networks:
            roboticWeb:
                ipv4_address: 172.20.0.2
        tty: true
        
    nginx:
        restart: always
        container_name: 'nginx'
        image: 'nginx:latest'
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            roboticWeb:
                ipv4_address: 172.20.0.3

    mongodb:
        image: 'mongo:latest'
        container_name: 'mongodb'
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGO_USER="Robotlab"
            - MONGO_PASS="Server201901"
        expose:
            - 27017
        volumes:
            - ./data/db:/data/db
        networks:
            roboticWeb:
                ipv4_address: 172.20.0.4
        command: mongod --smallfiles --logpath=/dev/null
        
networks:
    roboticWeb:
        driver: "bridge"
